# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  [push, fork]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: |
        dotnet test --no-build --verbosity normal --logger "html;logfilename=testResults.html" || echo $? > __result.txt
        if [ ! -f __result.txt ] 
        then 
          echo 0 > __result.txt
        fi
    
    - name: Create index file
      run: |
        __STUDENT_INFO__=$(grep -iEo "new\s+Information\(.*\)" Laboratorio0*/Information.cs | sed -e 's|",[[:space:]]*|?|g' | sed -e 's/new Information//g' | sed 's/(//g' | sed 's/)//g')
        __STUDENT_NAME__=$(echo $__STUDENT_INFO__ | cut -d '?' -f 1 | sed 's/"//g')
        echo $__STUDENT_NAME__
        __STUDENT_CARNET__=$(echo $__STUDENT_INFO__ | cut -d '?' -f 2 | sed 's/"//g')
        echo $__STUDENT_CARNET__
        __STUDENT_SECTION__=$(echo $__STUDENT_INFO__ | cut -d '?' -f 3 | sed 's/"//g')
        echo $__STUDENT_SECTION__
        mkdir -p public
        mv .index.html ./public/index.html
        sed -i "s/__STUDENT_NAME__/$__STUDENT_NAME__/g" ./public/index.html
        sed -i "s/__STUDENT_CARNET__/$__STUDENT_CARNET__/g" ./public/index.html
        sed -i "s/__STUDENT_SECTION__/$__STUDENT_SECTION__/g" ./public/index.html
        mv ./Laboratorio05Tests/TestResults/* ./public/

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: main  # default: gh-pages
        publish_dir: ./public
    
    - name: Exit with result code
      run: |
        __RESULT_CODE__=$(cat __result.txt)
        rm -f __result.txt
        exit $__RESULT_CODE__
    
    - name: Print if no failure
      run: echo "100%!"